basic_settings:
  site_title: ObjectFolder
  favicon_image: /assets/img/objectfolder_logo_1.png

header_settings:
  logo_image: /assets/img/objectfolder_logo_2.png
  mobile_logo_image: assets/img/objectfolder_logo_2.png
  # Choose a color for your header [blue, dark, light].
  theme: light
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landingb

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /

    - title: 'ObjectFolder-Real'
      submenu_items:
      - title: 'Download'
        url: /objectfolder-real-download
        icon: # TODO
      - title: 'Interactive Demos'
        url: /objectfolder-real
        icon: # TODO
    
    - title: 'ObjectFolder 2.0'
      submenu_items:
      - title: 'Download'
        url: /objectfolder2-0-download
        icon: # TODO
      - title: 'Code'
        url: https://github.com/rhgao/ObjectFolder
        icon: # TODO
      - title: 'Supplementary Video'
        url: https://www.youtube.com/watch?v=e5aToT3LkRA
        icon: # TODO

    - title: 'Benchmarks'
      submenu_items:
      - title: 'Code'
        url: https://github.com/objectfolder
        icon: # TODO
      - title: 'Object Recognition'
        url: /benchmark-recognition
        icon: # TODO
      - title: 'Object Reconstruction'
        url: /benchmark-reconstruction
        icon: # TODO
      - title: 'Object Manipulation'
        url: /benchmark-manipulation
        icon: # TODO

    # - title: 'Publications'
    #   url: /publications

footer_settings:
  footer_tagline: ObjectFolder is developed by the Stanford Vision and Learning Lab and collaborators.

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://github.com/StanfordVL/behavior'
  reddit_url: ''
  linkedin_url: ''

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 
